service: dnipro-slay-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x

functions:
  api:
    handler: dist/index.handler
    events:
      - httpApi: '*'
  parse:
    handler: dist/handlers/parseHandler.parseHandler
    events:
      - schedule:
          rate: cron(0 0,6,12,18 * * ? *)
          enabled: true
